// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9YC2K6jtBEP5G1hIYtRDl8U_vXjQsNIo',
    appId: '1:938741497193:web:b3b2ab7cc4437f37ba11f8',
    messagingSenderId: '938741497193',
    projectId: 'appp-a4450',
    authDomain: 'appp-a4450.firebaseapp.com',
    databaseURL: 'https://appp-a4450-default-rtdb.firebaseio.com',
    storageBucket: 'appp-a4450.firebasestorage.app',
    measurementId: 'G-G8MG22JGZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8HWBuiKGJE9eM5hLPf82uB1g5FDlQb3E',
    appId: '1:1026627253984:android:0d5d1926dddc909642c285',
    messagingSenderId: '938741497193',
    projectId: 'gold-57e14',
    databaseURL: 'https://gold-57e14-default-rtdb.firebaseio.com',
    storageBucket: 'gold-57e14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmSk1xWctUB9Z-uFawcTn49xe-VIx2acM',
    appId: '1:938741497193:ios:f6070de86441d44cba11f8',
    messagingSenderId: '938741497193',
    projectId: 'appp-a4450',
    databaseURL: 'https://appp-a4450-default-rtdb.firebaseio.com',
    storageBucket: 'appp-a4450.firebasestorage.app',
    iosBundleId: 'com.example.gasstation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmSk1xWctUB9Z-uFawcTn49xe-VIx2acM',
    appId: '1:938741497193:ios:f6070de86441d44cba11f8',
    messagingSenderId: '938741497193',
    projectId: 'appp-a4450',
    databaseURL: 'https://appp-a4450-default-rtdb.firebaseio.com',
    storageBucket: 'appp-a4450.firebasestorage.app',
    iosBundleId: 'com.example.gasstation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9YC2K6jtBEP5G1hIYtRDl8U_vXjQsNIo',
    appId: '1:938741497193:web:624bba26020c90eaba11f8',
    messagingSenderId: '938741497193',
    projectId: 'appp-a4450',
    authDomain: 'appp-a4450.firebaseapp.com',
    databaseURL: 'https://appp-a4450-default-rtdb.firebaseio.com',
    storageBucket: 'appp-a4450.firebasestorage.app',
    measurementId: 'G-M39L1PJPXE',
  );
}
